#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef RAVELINCORE_SWIFT_H
#define RAVELINCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RavelinCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class NSString;

SWIFT_CLASS_NAMED("Ravelin")
@interface Ravelin : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// The singleton instance of the class
/// remark:
/// You will need to set apiKey before use or use createInstance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Ravelin * _Nonnull shared;)
+ (Ravelin * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Your chosen orderId
@property (nonatomic, copy) NSString * _Nullable orderId;
/// Your chosen customerId
@property (nonatomic, copy) NSString * _Nullable customerId;
/// Your chosen tempCustomerId
@property (nonatomic, copy) NSString * _Nullable tempCustomerId;
/// The Ravelin generated deviceId
@property (nonatomic, readonly, copy) NSString * _Nullable deviceId;
/// The Ravelin generated sessionId
@property (nonatomic, readonly, copy) NSString * _Nullable sessionId;
/// The public API key from your Ravelin dashboard
@property (nonatomic, readonly, copy) NSString * _Nullable apiKey;
/// The RSA key from your Ravelin dashboard
@property (nonatomic, readonly, copy) NSString * _Nullable rsaKey;
/// Create a singleton instance of the Ravelin sdk with your public key
/// remark:
/// Use this method when using RavelinSDK in your app for the first time
/// \param apiKey The public API key from your Ravelin dashboard
///
///
/// returns:
/// The singleton instance of the class
+ (Ravelin * _Nonnull)createInstance:(NSString * _Nonnull)apiKey SWIFT_WARN_UNUSED_RESULT;
/// Create a singleton instance of the Ravelin sdk with your public key
/// remark:
/// Use this method when using RavelinSDK in your app for the first time
/// \param apiKey The public API key from your Ravelin dashboard
///
/// \param rsaKey The RSA key from your Ravelin dashboard
///
/// \param enableRetry enable/disbale retry events
///
///
/// returns:
/// The singleton instance of the class
+ (Ravelin * _Nonnull)createInstanceWithApiKey:(NSString * _Nonnull)apiKey rsaKey:(NSString * _Nullable)rsaKey enableRetry:(BOOL)enableRetry SWIFT_WARN_UNUSED_RESULT;
@end


@class NSNumber;
@class NSData;
@class NSURLResponse;

@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track add to cart event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
/// \param quantity Quantity of the item
///
- (void)trackAddToCartWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName quantity:(NSNumber * _Nullable)quantity;
/// Sends a track add to cart event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
/// \param quantity Quantity of the item
///
/// \param completionHandler Completion handler for the response
///
- (void)trackAddToCartWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName quantity:(NSNumber * _Nullable)quantity completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param eventName The name of the event
///
/// \param eventProperties A dictionary of meta data to send with the event
///
- (void)track:(NSString * _Nullable)pageTitle eventName:(NSString * _Nullable)eventName eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties;
/// Sends a track event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param eventName The name of the event
///
/// \param eventProperties A dictionary of meta data to send with the event
///
/// \param completionHandler Completion handler for the response
///
- (void)track:(NSString * _Nullable)pageTitle eventName:(NSString * _Nullable)eventName eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track add to wishlist event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
- (void)trackAddToWishlistWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName;
/// Sends a track add to wishlist event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
/// \param completionHandler Completion handler for the response
///
- (void)trackAddToWishlistWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track remove from wishlist event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
- (void)trackRemoveFromWishlistWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName;
/// Sends a track remove from wishlist event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
/// \param completionHandler Completion handler for the response
///
- (void)trackRemoveFromWishlistWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track search event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param searchValue The searched term
///
- (void)trackSearch:(NSString * _Nullable)pageTitle searchValue:(NSString * _Nullable)searchValue;
/// Sends a track search event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param searchValue The searched term
///
/// \param completionHandler Completion handler for the response
///
- (void)trackSearch:(NSString * _Nullable)pageTitle searchValue:(NSString * _Nullable)searchValue completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end



@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track remove from cart event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
/// \param quantity Quantity of the item
///
- (void)trackRemoveFromCartWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName quantity:(NSNumber * _Nullable)quantity;
/// Sends a track remove from cart event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param itemName Name of the item
///
/// \param quantity Quantity of the item
///
/// \param completionHandler Completion handler for the response
///
- (void)trackRemoveFromCartWithPageTitle:(NSString * _Nullable)pageTitle itemName:(NSString * _Nullable)itemName quantity:(NSNumber * _Nullable)quantity completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track view content event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param contentType The type of the content
///
- (void)trackViewContent:(NSString * _Nullable)pageTitle contentType:(NSString * _Nullable)contentType;
/// Sends a track view content event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param contentType The type of the content
///
/// \param completionHandler Completion handler for the response
///
- (void)trackViewContent:(NSString * _Nullable)pageTitle contentType:(NSString * _Nullable)contentType completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track selected option event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param option The name of the option
///
/// \param optionValue The value of the option
///
- (void)trackSelectOption:(NSString * _Nullable)pageTitle option:(NSString * _Nullable)option optionValue:(NSString * _Nullable)optionValue;
/// Sends a track selected option event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param option The name of the option
///
/// \param optionValue The value of the option
///
/// \param completionHandler Completion handler for the response
///
- (void)trackSelectOption:(NSString * _Nullable)pageTitle option:(NSString * _Nullable)option optionValue:(NSString * _Nullable)optionValue completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Fingerprints the device and sends results to Ravelin
- (void)trackFingerprint;
/// Fingerprints the device and sends results to Ravelin
/// \param completionHandler Completion handler for the response
///
- (void)trackFingerprint:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
/// Fingerprints the device and sends results to Ravelin
/// \param customerId The customerId to set for this device fingerprint.
///
/// \param completionHandler Completion handler for the response
///
- (void)trackFingerprint:(NSString * _Nullable)customerId completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track page event to Ravelin
/// \param pageTitle The title of the current page
///
- (void)trackPage:(NSString * _Nullable)pageTitle;
/// Sends a track page event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param eventProperties A dictionary of meta data to send with the event
///
- (void)trackPage:(NSString * _Nullable)pageTitle eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties;
/// Sends a track page event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param eventProperties A dictionary of meta data to send with the event
///
/// \param completionHandler Completion handler for the response
///
- (void)trackPage:(NSString * _Nullable)pageTitle eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Ends current Ravelin session and sends logout event to Ravelin
/// \param pageTitle The title of the current page
///
- (void)trackLogout:(NSString * _Nullable)pageTitle;
/// Ends current Ravelin session and sends logout event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param eventProperties A dictionary of meta data to send with the event
///
- (void)trackLogout:(NSString * _Nullable)pageTitle eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties;
/// Ends current Ravelin session and sends logout event to Ravelin
/// \param pageTitle The title of the current page
///
/// \param eventProperties A dictionary of meta data to send with the event
///
/// \param completionHandler Completion handler for the response
///
- (void)trackLogout:(NSString * _Nullable)pageTitle eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end


@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
/// Sends a track login event to Ravelin and sends customerId automatically if set
/// \param pageTitle The title of the current page
///
- (void)trackLogin:(NSString * _Nullable)pageTitle;
/// Sends a track login event to Ravelin and sends customerId automatically if set
/// \param pageTitle The title of the current page
///
/// \param eventProperties A dictionary of meta data to send with the event
///
- (void)trackLogin:(NSString * _Nullable)pageTitle eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties;
/// Sends a track login event to Ravelin and sends customerId automatically if set
/// \param pageTitle The title of the current page
///
/// \param eventProperties A dictionary of meta data to send with the event
///
/// \param completionHandler Completion handler for the response
///
- (void)trackLogin:(NSString * _Nullable)pageTitle eventProperties:(NSDictionary<NSString *, id> * _Nullable)eventProperties completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSURLResponse * _Nullable, NSError * _Nullable))completionHandler;
@end

@class WKUserScript;
@class WKWebViewConfiguration;
@class NSHTTPCookie;
@class WKWebView;

@interface Ravelin (SWIFT_EXTENSION(RavelinCore))
- (NSString * _Nullable)makeDeviceIdScriptString SWIFT_WARN_UNUSED_RESULT;
- (WKUserScript * _Nullable)makeDeviceIdScript SWIFT_WARN_UNUSED_RESULT;
- (BOOL)addDeviceIdScriptWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
- (NSHTTPCookie * _Nullable)makeDeviceIdCookieWithDomain:(NSString * _Nonnull)domain SWIFT_WARN_UNUSED_RESULT;
- (void)addRavelinDeviceIdCookieWithWebView:(WKWebView * _Nonnull)webView domain:(NSString * _Nonnull)domain completionHandler:(void (^ _Nullable)(NSHTTPCookie * _Nullable))completionHandler;
@end




#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
